# アプリケーション名
spring.application.name=salon-work-pro

# MySQL接続先
spring.datasource.url=jdbc:mysql://localhost:3306/salon_work_pro

# ユーザー名
spring.datasource.username=root

# パスワード
spring.datasource.password=syuto1878

# MySQLドライバー
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate設定
spring.jpa.hibernate.ddl-auto=update

# 実行SQLをコンソールへ表示
spring.jpa.show-sql=true